
REVOKE EXECUTE ON FUNCTION public.admin_list_temp_passwords() FROM anon;
REVOKE EXECUTE ON FUNCTION public.audit_attendance_event() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.audit_document_decision() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.audit_lead_cancel_or_delete() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.audit_lead_changes() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.audit_project_delete() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.audit_project_status_change() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.audit_salary_profile() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.bike_km_for_day(uuid, date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.bike_km_for_month(uuid, integer, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.bike_km_summary(uuid, integer, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.can_advance_project(uuid, project_status) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_duplicate_lead(text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.clear_temp_password_on_complete() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.complete_staff_password_setup() FROM anon;
REVOKE EXECUTE ON FUNCTION public.compute_salary(uuid, integer, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.count_admins() FROM anon;
REVOKE EXECUTE ON FUNCTION public.dispatch_push_on_notification() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.enforce_project_stage_gate() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.ensure_single_default_bank() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_project_code() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_quotation_number() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_assignable_sales_persons() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_last_saved_bike_reading(uuid, uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_lead_people(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_project_timeline(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_staff_public(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_role(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_lead_assignment() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_project_assignment() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_user_event(text, jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_salary_paid(uuid, numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_document_rejected() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_event_rejected() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_lead_assigned() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_project_status_change() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_task_assigned() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_worker_assigned() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.project_stage_requirements(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.punch_attendance(text, numeric, numeric, numeric, text, numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.quotation_totals() FROM anon;
REVOKE EXECUTE ON FUNCTION public.request_special_punch_out(numeric, numeric, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reupload_event_image(uuid, text, numeric, numeric, numeric, numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.review_punch_out_request(uuid, boolean, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.staff_performance(date, date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_attendance_from_event() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.task_status_transition() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_attendance_bike_reading() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_field_visit_bike_reading() FROM anon, authenticated;
